spring:
  application:
    name: date-ui
  jackson:
    serialization:
      indent-output: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
ribbon:
  http:
    client:
      enabled: true
---
spring:
  profiles: cloud
eureka:
  client:
    service-url:
      defaultZone: http://eureka-kdv.cfapps.io/eureka/
  instance:
    hostname: ${vcap.application.uris[0]}
    non-secure-port: 80
  