server:
  port: 8001
spring:
  application:
    name: date-service
  jackson:
    serialization:
      indent-output: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    root: error
---
spring:
  profiles: cloud
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-kdv.cfapps.io/eureka/
  instance:
    hostname: ${vcap.application.uris[0]}
    non-secure-port: 80
  